#!/usr/bin/env tclsh
#
# extract_instruction_table.tcl — Stream 3 (K) — parse Tcl 8.6's
# tclInstructionTable[] (in generic/tclCompile.c) and emit a Tcl-readable
# dict. The dict is the empirical source of authoritative pop/push counts
# the walker uses for Tier 2 (Tcl-known but no walker handler).
#
# Why pure Tcl (not Python) — keeps the P1 toolchain monolithic; one
# `tclsh` runs every probe, fixture, and gate. The C grammar we need to
# parse is regular (one row per `{"name", N, S, K, {OPERAND...}}` pattern)
# so Tcl regex is sufficient.
#
# Usage:
#   tclsh validation/probes/extract_instruction_table.tcl \
#       /tmp/tcl-src/tcl8.6.14/generic/tclCompile.c \
#       validation/probes/INSTRUCTION_TABLE_8_6_14.tcl
#
# Output format (sourced by opcode_walker.tcl + opcode_coverage_probe.tcl):
#   set ::jcm::disasm::tcltable::TCL_INSTRUCTION_TABLE {
#       done           {1 -1 0 OPERAND_NONE}
#       push1          {2  1 1 OPERAND_LIT1}
#       ...
#   }
#
# Per-row tuple = {numBytes stackEffect numOperands operand_types_csv}.
# stackEffect is signed int OR the literal token INT_MIN — the walker
# treats INT_MIN as "operand-driven" and reads numOperands + opTypes
# instead. (See _lookup_effect Tier 2 path.)

if {$::argc != 2} {
    puts stderr "Usage: extract_instruction_table.tcl SRC.c OUT.tcl"
    exit 2
}

set src_path [lindex $::argv 0]
set out_path [lindex $::argv 1]

set fp [open $src_path r]
fconfigure $fp -encoding utf-8
set src [read $fp]
close $fp

# Locate the table block: starts at the line containing the opening
# brace of `InstructionDesc const tclInstructionTable[] = {` and ends at
# the first `^};` on its own (column-0 close brace + semicolon).
set start_re "InstructionDesc\\s+const\\s+tclInstructionTable\\\[\\\]\\s*=\\s*\\{"
set end_re   "(?n)^\\};"
set start_match ""
if {![regexp -indices $start_re $src start_match]} {
    puts stderr "ERROR: could not locate tclInstructionTable\[\] header"
    exit 1
}
set table_start [expr {[lindex $start_match 1] + 1}]
set tail [string range $src $table_start end]
set end_match ""
if {![regexp -indices $end_re $tail end_match]} {
    puts stderr "ERROR: could not locate end of tclInstructionTable\[\]"
    exit 1
}
set table_end [lindex $end_match 0]
set table_block [string range $tail 0 [expr {$table_end - 1}]]

# Strip C block comments — they contain commas and braces that confuse
# the row parser.
regsub -all {/\*.*?\*/} $table_block "" table_block

# Match each row:
#   {"name",  N,  S,  K, {OPERAND_X[, OPERAND_Y]}}
# Capture: name, numBytes, stackEffect (signed digits OR INT_MIN),
# numOperands, opTypes braces content.
set row_re "\\{\\s*\"(\[^\"\]+)\"\\s*,\\s*(\[0-9\]+)\\s*,\\s*(\[+\\-\]?\[0-9\]+|INT_MIN)\\s*,\\s*(\[0-9\]+)\\s*,\\s*\\{(\[^\}\]*)\\}\\s*\\}"

set rows [list]
set name_set [dict create]
set match_count 0
set offset 0
while {[regexp -indices -start $offset $row_re $table_block match \
        nm nb se no ot]} {
    incr match_count
    set name      [string range $table_block {*}$nm]
    set numbytes  [string range $table_block {*}$nb]
    set stackeff  [string range $table_block {*}$se]
    set nopnds    [string range $table_block {*}$no]
    set optypes_raw [string range $table_block {*}$ot]
    # Normalize stackEffect: drop a leading "+".
    if {[string index $stackeff 0] eq "+"} {
        set stackeff [string range $stackeff 1 end]
    }
    # Normalize opTypes: comma-split, trim each, join with comma+space.
    set parts [list]
    foreach part [split $optypes_raw ","] {
        set p [string trim $part]
        if {$p ne ""} { lappend parts $p }
    }
    set optypes_csv [join $parts ","]
    if {[dict exists $name_set $name]} {
        puts stderr "WARN: duplicate row for $name — skipping second"
    } else {
        dict set name_set $name 1
        lappend rows $name $numbytes $stackeff $nopnds $optypes_csv
    }
    set offset [expr {[lindex $match 1] + 1}]
}

if {$match_count == 0} {
    puts stderr "ERROR: regex matched zero rows — grammar drift?"
    exit 1
}

# Emit the file.
set out [open $out_path w]
fconfigure $out -encoding utf-8
puts $out "# AUTO-GENERATED by validation/probes/extract_instruction_table.tcl."
puts $out "# Source: tcl8.6.14/generic/tclCompile.c (tclInstructionTable\[\])."
puts $out "# Do NOT edit by hand — re-run the extractor against a refreshed"
puts $out "# Tcl source tree if upgrading."
puts $out "#"
puts $out "# Per-row tuple = {numBytes stackEffect numOperands operand_types_csv}."
puts $out "# stackEffect: signed integer OR literal INT_MIN (operand-driven)."
puts $out ""
puts $out "namespace eval ::jcm::disasm::tcltable {"
puts $out "    variable TCL_INSTRUCTION_TABLE"
puts $out "}"
puts $out ""
puts $out "set ::jcm::disasm::tcltable::TCL_INSTRUCTION_TABLE \{"
foreach {name numbytes stackeff nopnds optypes_csv} $rows {
    puts $out [format "    %-22s {%s %s %s %s}" \
        $name $numbytes $stackeff $nopnds $optypes_csv]
}
puts $out "\}"
close $out

set total [expr {[llength $rows] / 5}]
puts "Extracted $total rows from $src_path"
puts "Wrote $out_path"

# Smoke-check: a few well-known opcodes must be present.
set required {done push1 invokeStk1 invokeStk4 invokeReplace evalStk \
    add sub mult div lshift over strindex listNotIn arrayExistsStk \
    verifyDict strneq}
set missing [list]
foreach r $required {
    if {![dict exists $name_set $r]} { lappend missing $r }
}
if {[llength $missing] > 0} {
    puts stderr "WARN: required opcodes missing from extraction: $missing"
    exit 1
}
puts "Smoke-check OK: all P1.3-required opcodes present"
